In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../Data/catanSim1.json")

In [4]:
df = pd.json_normalize(df['_default'])

In [6]:
df.to_csv("../Data/catanSim1.csv", index=False)

In [2]:
df = pd.read_csv("../Data/catanSim1.csv")

In [3]:
df

,r_t,b_t,o_t,w_t,P0_ACTUAL_VPS,P0_PUBLIC_VPS,P0_HAS_ARMY,P0_HAS_ROAD,P0_ROADS_LEFT,P0_SETTLEMENTS_LEFT,...,"EDGE(51, 52)_P3_ROAD","EDGE(52, 53)_P3_ROAD",BANK_DEV_CARDS,IS_MOVING_ROBBER,IS_DISCARDING,BANK_WOOD,BANK_BRICK,BANK_SHEEP,BANK_WHEAT,BANK_ORE
0,0.688716,0.591236,0.863284,0.766884,5,5,False,False,8,0,...,False,False,21,False,False,18,11,12,13,16
1,0.623186,0.846478,0.776447,0.499238,10,10,False,False,0,1,...,True,True,22,False,False,19,18,13,8,5
2,0.336963,0.872392,0.311497,0.819053,7,7,False,False,6,4,...,False,False,20,False,False,9,15,12,14,3
3,0.720148,0.539848,0.938003,0.668045,10,10,False,True,3,1,...,False,False,24,False,False,15,14,13,13,13
4,0.723964,0.859077,0.671723,0.638369,10,10,False,True,0,1,...,False,False,24,False,False,9,6,5,14,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.700235,0.722901,0.751937,0.909875,10,10,False,True,0,1,...,False,False,25,False,False,13,18,14,15,13
3996,0.790124,0.796962,0.873724,0.530257,10,8,False,False,8,5,...,False,False,23,False,False,12,14,8,12,12
3997,0.669046,0.962964,0.552439,0.577321,8,8,False,False,5,1,...,False,False,22,False,False,13,18,13,17,5
3998,0.689082,0.689534,0.588213,0.406422,6,4,False,False,7,3,...,False,False,20,False,False,13,13,13,15,11
3999,0.637763,0.508873,0.896065,0.517627,11,11,False,True,7,4,...,False,False,24,False,False,19,16,19,13,11

In [9]:
with open("../Data/columns.txt", "w") as f:
    for col in df.columns:
        f.write(col + "\n")

In [11]:
with open("../Data/columns.txt", "r") as f:
    colSubs = f.readlines()

In [13]:
colSubs = [col.strip() for col in colSubs]

In [15]:
df = df[colSubs]

In [17]:
import numpy as np

In [ ]:
def calc_score(row, num):
    

P0_ACTUAL_VPS
P0_PUBLIC_VPS
P0_HAS_ARMY
P0_HAS_ROAD
P0_ROADS_LEFT
P0_SETTLEMENTS_LEFT
P0_CITIES_LEFT
P0_HAS_ROLLED
P0_LONGEST_ROAD_LENGTH

P0_WOOD_IN_HAND
P0_BRICK_IN_HAND
P0_SHEEP_IN_HAND
P0_WHEAT_IN_HAND
P0_ORE_IN_HAND
P0_KNIGHT_IN_HAND
P0_YEAR_OF_PLENTY_IN_HAND
P0_MONOPOLY_IN_HAND
P0_ROAD_BUILDING_IN_HAND
P0_VICTORY_POINT_IN_HAND
P0_HAS_PLAYED_DEVELOPMENT_CARD_IN_TURN
P0_KNIGHT_PLAYED
P0_YEAR_OF_PLENTY_PLAYED
P0_MONOPOLY_PLAYED
P0_ROAD_BUILDING_PLAYED
P0_NUM_RESOURCES_IN_HAND
P0_NUM_DEVS_IN_HAND

In [16]:
df["score"] = df.apply(calc_score, axis=1)

,r_t,b_t,o_t,w_t,P0_ACTUAL_VPS,P0_PUBLIC_VPS,P0_HAS_ARMY,P0_HAS_ROAD,P0_ROADS_LEFT,P0_SETTLEMENTS_LEFT,...,P3_NUM_RESOURCES_IN_HAND,P3_NUM_DEVS_IN_HAND,BANK_DEV_CARDS,IS_MOVING_ROBBER,IS_DISCARDING,BANK_WOOD,BANK_BRICK,BANK_SHEEP,BANK_WHEAT,BANK_ORE
0,0.688716,0.591236,0.863284,0.766884,5,5,False,False,8,0,...,7,2,21,False,False,18,11,12,13,16
1,0.623186,0.846478,0.776447,0.499238,10,10,False,False,0,1,...,5,0,22,False,False,19,18,13,8,5
2,0.336963,0.872392,0.311497,0.819053,7,7,False,False,6,4,...,20,0,20,False,False,9,15,12,14,3
3,0.720148,0.539848,0.938003,0.668045,10,10,False,True,3,1,...,4,0,24,False,False,15,14,13,13,13
4,0.723964,0.859077,0.671723,0.638369,10,10,False,True,0,1,...,7,1,24,False,False,9,6,5,14,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.700235,0.722901,0.751937,0.909875,10,10,False,True,0,1,...,6,0,25,False,False,13,18,14,15,13
3996,0.790124,0.796962,0.873724,0.530257,10,8,False,False,8,5,...,5,0,23,False,False,12,14,8,12,12
3997,0.669046,0.962964,0.552439,0.577321,8,8,False,False,5,1,...,6,1,22,False,False,13,18,13,17,5
3998,0.689082,0.689534,0.588213,0.406422,6,4,False,False,7,3,...,6,1,20,False,False,13,13,13,15,11
3999,0.637763,0.508873,0.896065,0.517627,11,11,False,True,7,4,...,5,0,24,False,False,19,16,19,13,11